"""Generate the Sphinx API index from top-level runtime modules."""

from __future__ import annotations

from pathlib import Path


DOCS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DOCS_DIR.parent
API_INDEX_PATH = DOCS_DIR / "api" / "index.rst"
EXCLUDED_MODULES = {"__init__", "conftest"}


def discover_module_names(project_root: Path) -> list[str]:
    """Return sorted runtime module names from the repository root.

    Parameters
    ----------
    project_root:
        Repository root to scan for top-level Python modules.

    Returns
    -------
    list[str]
        Alphabetically sorted module names suitable for ``autosummary``.
    """

    return sorted(
        path.stem
        for path in project_root.glob("*.py")
        if path.stem not in EXCLUDED_MODULES
        and not path.stem.startswith("_")
        and not path.stem.startswith("test_")
    )


def build_index_content(module_names: list[str]) -> str:
    """Build the generated ``docs/api/index.rst`` contents.

    Parameters
    ----------
    module_names:
        Module names to include in the generated autosummary list.

    Returns
    -------
    str
        Rendered reStructuredText content for the API index.
    """

    lines = [
        "API Reference",
        "=============",
        "",
        "The pages below are generated from the Python modules in the repository root.",
        "They reflect the current docstrings, type hints, and member structure of the",
        "runtime code.",
        "",
        ".. This file is generated by ``docs/generate_api_index.py``.",
        "",
        ".. autosummary::",
        "   :toctree: generated",
        "",
    ]
    lines.extend(f"   {module_name}" for module_name in module_names)
    lines.append("")
    return "\n".join(lines)


def write_index(path: Path, content: str) -> bool:
    """Write the generated API index if its contents changed.

    Parameters
    ----------
    path:
        Output path for the generated API index.
    content:
        Rendered file contents to write.

    Returns
    -------
    bool
        ``True`` when the file changed, otherwise ``False``.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    previous = path.read_text(encoding="utf-8") if path.exists() else None
    if previous == content:
        return False

    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    """Regenerate ``docs/api/index.rst`` from the current module list."""

    module_names = discover_module_names(PROJECT_ROOT)
    changed = write_index(API_INDEX_PATH, build_index_content(module_names))
    state = "updated" if changed else "already up to date"
    print(f"{API_INDEX_PATH.relative_to(PROJECT_ROOT)} {state} ({len(module_names)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
